-- =====================================================================
-- F226 / BT713 — claude.work_items unified table
-- =====================================================================
-- Purpose:
--   Phase 1 schema migration for the work-items unification (FB316).
--   Creates a single addressable table that will absorb features +
--   build_tasks + feedback + todos + reminders behind one short-code
--   sequence (`W###`). This migration is ADDITIVE only — it does not
--   touch the legacy tables. Backfill, dual-write, and primary-flip
--   ship in F228 / F229.
--
-- Design baseline:
--   - workfile component=work-items-unification, title="F226 master design …"
--   - workfile component=work-items-unification, title="… DECISIONS LOCKED 2026-05-02 …"
--   - research-validation appendix promotes verification/files_affected/
--     plan_data/due_at/estimated_hours/actual_hours/completion_percentage
--     to typed columns (Jira-attribute-sprawl mitigation).
--
-- Idempotency:
--   - CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS throughout.
--   - column_registry rows use ON CONFLICT (table_name, column_name)
--     DO UPDATE so re-running this migration converges, never duplicates.
--   - Re-running this file produces no diffs once applied.
--
-- BT714 (sidecar work_item_code_history table) ships separately and is
-- the canonical home for legacy short codes (FB###/F###/BT###/RM###).
-- This file therefore does NOT add legacy_short_code / legacy_table
-- columns to claude.work_items — those are superseded by the sidecar.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. claude.work_items — unified table
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS claude.work_items (
    -- identity
    work_item_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    short_code              INT  NOT NULL UNIQUE
                                 GENERATED BY DEFAULT AS IDENTITY (START WITH 1),

    -- core
    title                   VARCHAR(500) NOT NULL,
    description             TEXT,
    kind                    VARCHAR(50)  NOT NULL,
    stage                   VARCHAR(50)  NOT NULL,
    priority                INT          NOT NULL DEFAULT 3,

    -- ownership / scope
    project_id              UUID NOT NULL REFERENCES claude.projects(project_id),
    owner_identity_id       UUID         REFERENCES claude.identities(identity_id),
    task_scope              VARCHAR(20),

    -- hierarchy
    parent_id               UUID         REFERENCES claude.work_items(work_item_id),
    source_id               UUID         REFERENCES claude.work_items(work_item_id),
    blocked_by_id           UUID         REFERENCES claude.work_items(work_item_id),

    -- session linkage
    created_session_id      UUID,
    completed_session_id    UUID,

    -- timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at              TIMESTAMPTZ,
    completed_at            TIMESTAMPTZ,

    -- typed columns promoted from JSONB attributes (research §A.2)
    verification            TEXT,
    files_affected          TEXT[],
    plan_data               JSONB,
    due_at                  TIMESTAMPTZ,
    estimated_hours         NUMERIC(8,2),
    actual_hours            NUMERIC(8,2),
    completion_percentage   INT,

    -- sparse / exploratory attributes (kind-specific, low-density)
    attributes              JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- soft delete + audit
    is_deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT chk_kind CHECK (kind IN (
        'bug','idea','improvement','design','change','question',
        'feature','refactor','infrastructure','documentation','stream',
        'task','reminder'
    )),
    CONSTRAINT chk_stage CHECK (stage IN (
        'raw','triaged','planned','in_progress','blocked','done','dropped','parked'
    )),
    CONSTRAINT chk_priority CHECK (priority BETWEEN 1 AND 5),
    CONSTRAINT chk_task_scope CHECK (
        task_scope IS NULL OR task_scope IN ('session','persistent')
    ),
    CONSTRAINT chk_completion_percentage CHECK (
        completion_percentage IS NULL OR completion_percentage BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_estimated_hours CHECK (
        estimated_hours IS NULL OR estimated_hours >= 0
    ),
    CONSTRAINT chk_actual_hours CHECK (
        actual_hours IS NULL OR actual_hours >= 0
    )
);

COMMENT ON TABLE claude.work_items IS
    'F226 (FB316) unified work-item store: replaces features+build_tasks+feedback+todos+reminders behind a single W### short_code. Phase 1 (BT713) ships the table empty and additive; backfill is BT717. See workfile component=work-items-unification for the canonical design.';

COMMENT ON COLUMN claude.work_items.short_code IS
    'F226: monotonically-increasing W### identifier for new rows. Backfill (BT717) inserts with explicit values up to MAX(existing) so the IDENTITY sequence resumes above the highest backfilled value.';

COMMENT ON COLUMN claude.work_items.kind IS
    'F226 vocabulary: 6 feedback kinds (bug/idea/improvement/design/change/question), 5 feature kinds (feature/refactor/infrastructure/documentation/stream), task, reminder.';

COMMENT ON COLUMN claude.work_items.stage IS
    'F226 single stage vocabulary across all kinds (raw/triaged/planned/in_progress/blocked/done/dropped/parked). Replaces per-table status columns. See §5 transition matrix in master design.';

COMMENT ON COLUMN claude.work_items.attributes IS
    'F226: sparse kind-specific fields. Promote to typed column when an attribute appears in >30% of rows of a kind for >30 days (research §A.2).';

-- ---------------------------------------------------------------------
-- 2. Indexes
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_wi_project_stage
    ON claude.work_items (project_id, stage)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_wi_kind
    ON claude.work_items (kind)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_wi_parent
    ON claude.work_items (parent_id);

CREATE INDEX IF NOT EXISTS idx_wi_source
    ON claude.work_items (source_id);

CREATE INDEX IF NOT EXISTS idx_wi_blocked_by
    ON claude.work_items (blocked_by_id);

CREATE INDEX IF NOT EXISTS idx_wi_due_at
    ON claude.work_items (due_at)
    WHERE kind = 'reminder' AND is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_wi_attributes_gin
    ON claude.work_items USING GIN (attributes);

CREATE INDEX IF NOT EXISTS idx_wi_short_code
    ON claude.work_items (short_code);

-- ---------------------------------------------------------------------
-- 3. updated_at maintenance trigger
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION claude.work_items_set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_work_items_set_updated_at ON claude.work_items;
CREATE TRIGGER trg_work_items_set_updated_at
    BEFORE UPDATE ON claude.work_items
    FOR EACH ROW EXECUTE FUNCTION claude.work_items_set_updated_at();

-- ---------------------------------------------------------------------
-- 4. column_registry rows for the constrained columns
-- ---------------------------------------------------------------------
INSERT INTO claude.column_registry
    (id, table_name, column_name, data_type, is_nullable,
     description, valid_values, default_value, constraints)
VALUES
    (gen_random_uuid(), 'work_items', 'kind', 'varchar', FALSE,
     'F226 work-item discriminator across feedback/features/build_tasks/reminders.',
     '["bug","idea","improvement","design","change","question","feature","refactor","infrastructure","documentation","stream","task","reminder"]'::jsonb,
     NULL,
     'CHECK (kind IN (...)) — see chk_kind on claude.work_items'),
    (gen_random_uuid(), 'work_items', 'stage', 'varchar', FALSE,
     'F226 single stage vocabulary across all kinds. Replaces per-table status columns.',
     '["raw","triaged","planned","in_progress","blocked","done","dropped","parked"]'::jsonb,
     NULL,
     'CHECK (stage IN (...)) — see chk_stage on claude.work_items'),
    (gen_random_uuid(), 'work_items', 'priority', 'integer', FALSE,
     'F226 priority 1-5 (1=critical, 5=backlog).',
     '[1,2,3,4,5]'::jsonb,
     '3',
     'CHECK (priority BETWEEN 1 AND 5)'),
    (gen_random_uuid(), 'work_items', 'task_scope', 'varchar', TRUE,
     'F226 task/reminder scope. session=ephemeral todo, persistent=cross-session work.',
     '["session","persistent"]'::jsonb,
     NULL,
     'CHECK (task_scope IS NULL OR task_scope IN (...))')
ON CONFLICT (table_name, column_name) DO UPDATE SET
    data_type     = EXCLUDED.data_type,
    is_nullable   = EXCLUDED.is_nullable,
    description   = EXCLUDED.description,
    valid_values  = EXCLUDED.valid_values,
    default_value = EXCLUDED.default_value,
    constraints   = EXCLUDED.constraints,
    updated_at    = now();
